@isTest
private class IntegrationAccountHelperTest {
	
	@isTest static void test_method_one() {
		IntegrationAccountHelper.Data dat = new IntegrationAccountHelper.Data();
		dat.name = 'asdasdasd';
		dat.customerId = 'asdasdasd';
		dat.magentoId = 'asdasdasd';
		dat.salesforceId = 'asdasdasd';
		dat.billing_street = 'asdasdasd';
		dat.billing_city = 'asdasdasd';
		dat.billing_country_id = 'asdasdasd';
		dat.billing_postcode = 'asdasdasd';
		dat.billing_region = 'asdasdasd';
		dat.billing_phone = 'asdasdasd';
		dat.billing_cell = 'asdasdasd';
		dat.email = 'asdasdasd';
		dat.firstname = 'asdasdasd';
		dat.lastname = 'asdasdasd';
		dat.phone = 'asdasdasd';
		dat.shipping_street = 'asdasdasd';
		dat.shipping_city = 'asdasdasd';
		dat.shipping_country_id = 'asdasdasd';
		dat.shipping_postcode = 'asdasdasd';
		dat.shipping_region = 'asdasdasd';
		dat.shipping_phone = 'asdasdasd';
		dat.shipping_cell = 'asdasdasd';
		dat.middlename = 'asdasdasd';
		dat.sales_rep_name = 'asdasdasd';
		dat.customergroup = 'asdasdasd';
		dat.company_name = 'asdasdasd';
		dat.magento_sales_rep_id = 'asdasdasd';
		dat.website_id = 'asdasdasd';

		IntegrationAccountHelper.Log log = new IntegrationAccountHelper.Log();
		log.Data = dat;
		log.LogID = 'asda';
		log.Process = 'asdasd';

	}
	
}