public class MagentoCustomerGenerator 
{
    public string firstname;
    public string lastname;
    public string email;
    public string website_id;
    public string group_id;
    
    public MagentoCustomerGenerator(string fname,string lname,string inputemail,string web,string groupid)
    {
        firstname=fname;
        lastname=lname;
        email=inputemail;
        website_id=web;
        group_id=groupid;     
    }
    
   
    
    
    
    
    
}