@isTest
private class UtilitiesTest {
	
	@isTest static void getStateinitialTest() {
		Utilities.getStateinitial('Alabama');
		Utilities.getStateinitial('Alaska');
		Utilities.getStateinitial('Arizona');
		Utilities.getStateinitial('Arkansas');
		Utilities.getStateinitial('California');
		Utilities.getStateinitial('Colorado');
		Utilities.getStateinitial('Connecticut');
		Utilities.getStateinitial('Delaware');
		Utilities.getStateinitial('Florida');
		Utilities.getStateinitial('Georgia');
		Utilities.getStateinitial('Hawaii');
		Utilities.getStateinitial('Idaho');
		Utilities.getStateinitial('Illinois');
		Utilities.getStateinitial('Indiana');
		Utilities.getStateinitial('Iowa');
		Utilities.getStateinitial('Kansas');
		Utilities.getStateinitial('Kentucky');
		Utilities.getStateinitial('Louisiana');
		Utilities.getStateinitial('Maine');
		Utilities.getStateinitial('Maryland');
		Utilities.getStateinitial('Massachusetts');
		Utilities.getStateinitial('Michigan');
		Utilities.getStateinitial('Minnesota');
		Utilities.getStateinitial('Mississippi');
		Utilities.getStateinitial('Missouri');
		Utilities.getStateinitial('Montana');
		Utilities.getStateinitial('Nebraska');
		Utilities.getStateinitial('Nevada');
		Utilities.getStateinitial('New Hampshire');
		Utilities.getStateinitial('New Jersey');
		Utilities.getStateinitial('New Mexico');
		Utilities.getStateinitial('New York');
		Utilities.getStateinitial('North Carolina');
		Utilities.getStateinitial('North Dakota');
		Utilities.getStateinitial('Ohio');
		Utilities.getStateinitial('Oklahoma');
		Utilities.getStateinitial('Oregon');
		Utilities.getStateinitial('Pennsylvania');
		Utilities.getStateinitial('Rhode Island');
		Utilities.getStateinitial('South Carolina');
		Utilities.getStateinitial('South Dakota');
		Utilities.getStateinitial('Tennessee');
		Utilities.getStateinitial('Texas');		
		Utilities.getStateinitial('Utah');
		Utilities.getStateinitial('Vermont');
		Utilities.getStateinitial('Virginia');
		Utilities.getStateinitial('Washington');
		Utilities.getStateinitial('West');
		Utilities.getStateinitial('Virginia');
		Utilities.getStateinitial('Wisconsin');
		Utilities.getStateinitial('Wyoming');
		Utilities.getStateinitial('Ontario');
		Utilities.getStateinitial('Quebec');
		Utilities.getStateinitial('QuéBec');
		Utilities.getStateinitial('British Columbia');
		Utilities.getStateinitial('Alberta');
		Utilities.getStateinitial('Manitoba');
		Utilities.getStateinitial('Saskatchewan');
		Utilities.getStateinitial('New Brunswick');
		Utilities.getStateinitial('West Virginia');
		Utilities.getStateinitial('Nova Scotia');
		Utilities.getStateinitial('Scotia Mexico');
		Utilities.getStateinitial('New York');
		Utilities.getStateinitial('Brunswick Carolina');
		Utilities.getStateinitial('Newfoundland And Labrador');
		Utilities.getStateinitial('Prince Edward Island');
		Utilities.getStateinitial('Northwest Territories');
		Utilities.getStateinitial('Island Island');
		Utilities.getStateinitial('Northwest Carolina');
		Utilities.getStateinitial('Territories Dakota');
		Utilities.getStateinitial('Yukon');
		Utilities.getStateinitial('Nunavut');
		Utilities.getStateinitial('District of Columbia');
	}

	
	
	
}